var listaDepalabras = ["Sangre", "Batalla", "Efecto", "Filete", "Choque", "Grano", "Cobre", "Manzana", "Cortina", 
"Musica", "Recreo", "Campana", "Viga", "Recompensa", "Ropa", "Sombrero", "Boligrafo", "Cantante", "Semana", 
"Truco", "Entrenador", "Accidente", "Cuidado", "Nuez", "Tomate", "Viaje", "Caracol", "Gusto", "Ataque", "Papa",
"Asistencia", "Arroz", "Experto", "Presentacion", "Cordon", "Pala", "Requerimiento", "Proteccion", "Tienda", 
"Instancia", "Modo", "Pez",  "Ayuda", "Curva", "Digestion", "Banda", "Television", "Borde", "Pendiente", 
"Camino", "Carne", "Tranquilo", "Jardin", "Palabra", "Guerra", "Desarrollo", "Realidad", "Baloncesto", "Punto", 
"Dolor", "Perro", "Trebol", "Protesta", "Fracaso", "Familia", "Dinero",  "Ajedrez", "Intencion", "Asociacion", 
"Crayon", "Aumento", "Perdida", "Orden", "Capitulo", "Reina", "Retroalimentacion", "Inversion", "Mueble", 
"Longitud", "Tela", "Descubrimiento", "Sesion", "Montaña", "Portero", "Criatura", "Cuarto", "Mantenimiento", 
"Seguridad", "Bodega", "Actor", "Matematicas", "Cancion", "Silla", "Hermano","Control", "Prioridad", "Emocion", 
"Gorra", "Vela", "Mancha", "Tierra", "Conejo", "Fuego", "Niño", "Dispositivo", "Dedo", "Personalidad", "Huevo", 
"Disco", "Sueter", "Aspecto", "Vista", "Vuelo", "Posicion", "Nube", "Apio", "Secretaria", "Crimen", "Cuenca", 
"Rama", "Arena", "Hijo", "Sombra", "Peso", "Sistema", "Politica", "Equipo", "Guante", "Vaca", "Ensalada", 
"Nacion", "Distancia", "Doctor", "Cuello", "Mejilla", "Analisis", "Angulo", "Novio", "Empleo", "Alambre", 
"Cebo", "Estallido", "Casa", "Tension", "Organizacion", "Variedad", "Accion", "Experiencia", "Martillo", 
"Extraño", "Tormenta", "Lluvia", "Pensamiento", "Paja", "Cara", "Moneda", "Centavo", "Escalon", "Software", 
"Cama", "Bufanda", "Mascara", "Lectura", "Industria", "Esperanza", "Campeonato", "Revolucion", "Puntada", 
"Alarma", "Rango", "Aritmetica", "Fruta", "Botella", "Ventana", "Hoyo", "Motor", "Repollo", "Mono", "Lapiz", 
"Vestir", "Enfermedad", "Regla", "Aire", "Niebla", "Detalle", "Calcetin", "Advertencia", "Vidrio", "Estofado", 
"Lino", "Expansion", "Volumen", "Caida", "Presencia", "Propietario", "Chispa", "Conocimiento", "Anuncio", 
"Iglesia", "Religion", "Interaccion", "Aparato", "Agua", "Granja", "Movimiento", "Gota", "Creencia", "Acero", 
"Sopa", "Crema", "Profesor", "Representante", "Creador", "Madre", "Pintura", "Pasillo", "Ganador", "Usuario", 
"Celebracion", "Director", "Colmillo", "Administracion", "Rastrillo", "Invierno", "Cosa", "Costa", "Trono", 
"Sociedad", "Percepcion", "Definicion", "Nota", "Filosofia", "Crecimiento", "Consecuencia", "Libro", "Telefono", 
"Arte", "Manopla", "Cubo", "Tecnologia", "Letra", "Empujar", "Azucar", "Gato", "Simpatia", "Condado", "Naturaleza", 
"Dificultad", "Vivienda", "Coche", "Avion", "Cuadrado", "Autopista", "Pago", "Tradicion", "Cuerpo", "Recomendacion", 
"Reunion", "Isla", "Precio", "Araña", "Posibilidad", "Labio", "Camioneta", "Union", "Interes", "Limite", "Base", 
"Cabello", "Membrillo", "Lampara", "Motivo", "Jabon", "Hombre", "Mendigo", "Pena", "Maestro", "Asiento", "Libertad", 
"Tiempo", "Boca", "Rana","Explicacion", "Cuna", "Devoto", "Horoscopo", "Creacion","Pais", "Serpiente", "Esfuerzo", 
"Titulo", "Boton", "Internet", "Terremoto", "Tarjeta", "Miedo", "Arbol", "Espacio", "Consejo", "Necesidad"];