var listaDepalabras = ["Sueño", "Batalla", "Elefante", "Filete", "Choque", "Granero", "Cobre", "Manzana", "Cortina",
    "Musica", "Recreo", "Campana", "Viga", "Recompensa", "Ropa", "Sombrero", "Boligrafo", "Cantante", "Semana",
    "Truco", "Entrenador", "Automovil", "Cuidado", "Nuez", "Tomate", "Viaje", "Caracol", "Gusto", "Ataque", "Tesoro",
    "Cactus", "Arroz", "Experto", "Documentacion", "Juguete", "Caballo", "Requerimiento", "Escudo", "Tienda",
    "Estancia", "Modo", "Pez", "Castillo", "Torre", "Dragon", "Sofa", "Television", "Estrella", "Institucion",
    "Camino", "Cohete", "Tranquilidad", "Jardin", "Flamenco", "Guerra", "Civilizacion", "Futbol", "Baloncesto", "Triangulo",
    "Dolor", "Perro", "Trebol", "Protesta", "Frasco", "Familia", "Dinero", "Ajedrez", "Ciencia", "Academia",
    "Crayon", "Tigre", "Palmera", "Orden", "Capitan", "Reina", "Retroalimentacion", "Inversion", "Mueble",
    "Caos", "Tela", "Descubrimiento", "Hallazgo", "Montaña", "Portero", "Criatura", "Cuarto", "Mantenimiento",
    "Seguridad", "Bodega", "Actor", "Matematicas", "Cancion", "Silla", "Hermano", "Control", "Prioridad", "Emocion",
    "Gloria", "Vela", "Mancha", "Tierra", "Conejo", "Fuego", "Niño", "Electrodomestico", "Dedo", "Personalidad", "Huevo",
    "Disco", "Sueter", "Jirafa", "Vista", "Vuelo", "Posicion", "Nube", "Apio", "Secretaria", "Crimen", "Cuenca",
    "Rama", "Arena", "Hijo", "Sombra", "Peso", "Sistema", "Politica", "Equipo", "Guante", "Vaca", "Ensalada",
    "Nacion", "Paraiso", "Doctor", "Cuello", "Mejilla", "Analisis", "Angulo", "Cielo", "Empleo", "Alambre",
    "Cebo", "Estallido", "Casa", "Tension", "Organizacion", "Servilleta", "Accion", "Experiencia", "Martillo",
    "Extraño", "Tormenta", "Lluvia", "Pensamiento", "Muelle", "Cara", "Moneda", "Centavo", "Escalon", "Software",
    "Cama", "Bufanda", "Mascara", "Lectura", "Industria", "Esperanza", "Campeonato", "Revolucion", "Calculadora",
    "Alarma", "Rango", "Aritmetica", "Fruta", "Botella", "Ventana", "Aguja", "Motor", "Repollo", "Mono", "Lapiz",
    "Vestido", "Selva", "Escuadra", "Aire", "Niebla", "Planeta", "Calcetin", "Advertencia", "Vidrio", "Estofado",
    "Lino", "Explosion", "Volumen", "Caida", "Presencia", "Propietario", "Chispa", "Conocimiento", "Anuncio",
    "Iglesia", "Religion", "Interaccion", "Aparato", "Agua", "Granja", "Movimiento", "Gota", "Creencia", "Acero",
    "Sopa", "Crema", "Profesor", "Representante", "Creador", "Madre", "Pintura", "Pasillo", "Ganador", "Enchufe",
    "Celebracion", "Director", "Colmillo", "Administracion", "Rastrillo", "Invierno", "Cocina", "Costa", "Trono",
    "Sociedad", "Gobierno", "Gorila", "Nota", "Filosofia", "Crecimiento", "Consecuencia", "Libro", "Telefono",
    "Arte", "Manopla", "Cubo", "Tecnologia", "Arpa", "Guitarra", "Azucar", "Gato", "Sonrisa", "Condado", "Naturaleza",
    "Dificultad", "Vivienda", "Coche", "Avion", "Cuadrado", "Autopista", "Salario", "Tradicion", "Constitucion", "Recomendacion",
    "Reunion", "Isla", "Precio", "Araña", "Posibilidad", "Cocodrilo", "Camioneta", "Union", "Interes", "Limite", "Base",
    "Cabello", "Membrillo", "Lampara", "Motivo", "Jabon", "Hombre", "Mendigo", "Pena", "Maestro", "Asiento", "Libertad",
    "Tiempo", "Boca", "Rana", "Explicacion", "Cuna", "Devoto", "Horoscopo", "Creacion", "Pais", "Serpiente", "Esfuerzo",
    "Titulo", "Boton", "Internet", "Terremoto", "Tarjeta", "Miedo", "Arbol", "Espacio", "Consejo", "Necesidad"];

    for (var i = 0; i < listaDepalabras.length; i++){
        listaDepalabras[i] = listaDepalabras[i].toUpperCase();
    }